services:
  - type: web
    name: bot-ultimate-prediction-api
    env: python
    plan: free
    buildCommand: pip install -r api/requirements.txt
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
